(function () {
  'use strict';

  /**
   * @ngdoc overview
   * @name petdom
   * @module petdom
   *
   * @description
   * # Main app module
   *
   * The main module for the fitcheck webapp
   */

  angular.module('petdom', [
    // External modules
    'ngRoute',
    'ngCookies',
    'ui.bootstrap',
    'google.places',

    // Templates module generated by grunt-angular-templates
    'petdom.templates',


    // Internal modules
    'petdom.layout',
    'petdom.initialise-petdom',
    'petdom.landing-page'
  ]);
})();
